global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your@gmail.com'
  smtp_auth_username: 'your@gmail.com'
  smtp_auth_password: 'your app password'   # Use Gmail App Password, not your main password
  smtp_require_tls: true

route:
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'target@gmail'
        send_resolved: true
